version: '3.2'
services:
    server:
        image: voting-server
        container_name: server
        volumes:
            - ./usr/src/app
        ports:
            - "8080:8080"
        depends_on:
            - mysql
    web:
        image: voting-web
        container_name: web
        volumes:
            - ./usr/src/web
        ports:
            - "8081:8080"
    mysql:
        image: mysql
        command: --init-file init.sql
        container_name: mysqldatabase
        ports:
            - "3306:3306"
        expose:
            - 3307
        volumes:
            - ./data:/var/lib/mysql
            - ./init.sql:/var/lib/mysql/init.sql
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=voting
