version: '3.2'
services:
    web:
        image: voting-web
        container_name: web
        volumes:
            - ./usr/src/web
        ports:
            - "8081:8080"
    server:
        image: voting-server
        container_name: server
        volumes:
            - ./usr/src/app
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        command: ["/wait-for-it.sh" ,"mysql:3306" ,"-t" ,"0" ,"--" ,"node" ,"src/server.js"]
    mysql:
        image: mysql
        container_name: mysqldatabase
        ports:
            - "3306:3306"
        expose:
            - 3306
        volumes:
            - ./data:/var/lib/mysql
            - ./mysql/init:/docker-entrypoint-initdb.d/
            - ./mysql/cnf/custom.cnf:/etc/mysql/conf.d/custom.cnf
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=voting
